# To install or update the pre-commit withe latest version
#
# In your terminal:
#
# pre-commit install
# pre-commit install-hooks
#
# To enable mypy type checking, run:

# `pre-commit install -t pre-push`

# This will install the mypy check as a push hook, so it won't run on every commit, only on push.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [push,manual,commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements

- repo: local
  hooks:
    - id: darker
      name: darker
      entry: "darker -c pyproject.toml"
      language: python
      pass_filenames: true
      types: [file, python]
      # these versions need to be the kept the same as those in requirements/requirements-lint.in
      additional_dependencies:
        - darker==1.7.1
        - black==23.3.0
        - ruff==0.0.277
      stages: [commit, manual]
